openapi: 3.0.0

paths: 
  /add:
    post:
      summary: accepts a transaction
      requestBody:
        description: transaction data
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transaction"
      responses:
        '200':
          description: transaction received
        default:
          description: unexpectedError

  /spend:
    post:
      summary: spends points
      requestBody:
        description: points to spend
        required: true
        content:
          application/json:
              schema:
                '$ref': "#/components/schemas/Points"
      responses:
        '200':
          description: points spent
          content:
            application/json:
              schema:
                '$ref': "#/components/schemas/PointsSpent"
        '400':
          description: unexpectedError

    /balance:
      get:
        summary: gets balance
        responses:
          '200':
            description: balance returned
            content:
              application/json:
                schema:
                  '$ref': "#/components/schemas/Balance"
          '400':
            content:
              text/plain:
                schema:
                  type: string
        
              
components:
  schemas:
    Transaction:
      type: object
      required:
      - payer
      - points
      - timestamp
      properties:
        payer:
          type: string
        points:
          type: int
        timestamp:
          type: string
    
    PointsSpent:
      type: object
      required:
        type: array
        items:
          type: object
          required:
          - payer
          - points
          properties:
            payer:
              type: string
            points:
              type: int

    Balance:
      type: string

    Points:
      type: int
          